name: Documentation Impact Detection

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  detect-impact:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Show PR Details
        run: |

          echo "PR:"
          echo "${{ github.event.pull_request.title }}"

          echo ""
          echo "Base Branch:"
          echo "${{ github.base_ref }}"

          echo ""
          echo "Head Branch:"
          echo "${{ github.head_ref }}"
